[book]
title = "ðŸ”° Neob Programmer's Reference Manual"
description = "The Neob Programming Language"
language = "en"
src = "src"
authors = [
  "Raul Bras",
  "Contributions from the Neob Community"
]

[output.html]
theme = "theme"
